// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6135.robot.subsystems.reserved;

import org.usfirst.frc.team6135.robot.RobotMap;
import org.usfirst.frc.team6135.robot.commands.*;
import org.usfirst.frc.team6135.robot.commands.reserved.stopIndexer;
import org.usfirst.frc.team6135.robot.subsystems.baseSubsystem;

import com.ctre.CANTalon;
import com.ctre.CANTalon.FeedbackDevice;

import edu.wpi.first.wpilibj.VictorSP;



/**
 *
 */
public class FuelIndexer extends baseSubsystem {

    private final CANTalon indexerTalon = RobotMap.fuelIndexerTalon;
    private final VictorSP indexerVictor = RobotMap.fuelIndexerVictor;
    
    public FuelIndexer()
    {
    	super("FuelIndexer");
    	indexerTalon.setFeedbackDevice(FeedbackDevice.QuadEncoder);
    	ifOn=false;
    }
    public void set(double s)
    {
    	indexerTalon.set(-s);
    	indexerVictor.set(s);
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        setDefaultCommand(new stopIndexer());
    }
	@Override
	public double getRPM() {
		return indexerTalon.getEncVelocity();
	}
}

