package org.usfirst.frc.team6135.robot;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// For example to map the left and right motors, you could define the
	// following variables to use with your drivetrain subsystem.
	// public static int leftMotor = 1;
	// public static int rightMotor = 2;

	// If you are using multiple modules, make sure to define both the port
	// number and the module. For example you with a rangefinder:
	// public static int rangefinderPort = 1;
	// public static int rangefinderModule = 1;
	//Ports
	//Motor controllers for driving
	public static final int rVicPort = 1;
	public static final int lVicPort = 0;
	
	//Encoders for distance and balancing motors
	public static final int rEnc1 = 2;
	public static final int rEnc2 = 3;
	public static final int lEnc1 = 0;
	public static final int lEnc2 = 1;
	
	//Photoelectric sensor
	public static final int photoElectricSensor = 4;
	
	//subsystem motor control
	public static CANTalon intakeTalon;
    public static CANTalon indexerTalon;
    public static Victor indexerVictor;
    public static CANTalon shooterTalon;
    public static CANTalon climberTalon;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	intakeTalon = new CANTalon(1); 
        LiveWindow.addActuator("Intake", "Talon", intakeTalon);
        
        indexerTalon = new CANTalon(2); 
        indexerVictor=new Victor(2);
        LiveWindow.addActuator("Indexer", "Talon", indexerTalon);
        
        shooterTalon = new CANTalon(3); 
        LiveWindow.addActuator("Shooter", "Talon", shooterTalon);
        
        climberTalon = new CANTalon(4);
        LiveWindow.addActuator("Climber", "Talon", climberTalon);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
