// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6135.robot.subsystems;

import org.usfirst.frc.team6135.robot.RobotMap;
import org.usfirst.frc.team6135.robot.commands.*;
import com.ctre.CANTalon;
import com.ctre.CANTalon.FeedbackDevice;

/**
 *
 */
public class Climber extends baseSubsystem {


    private final CANTalon climberTalon = RobotMap.climberTalon;

    public Climber()
    {
    	super("Climber");
    	climberTalon.setFeedbackDevice(FeedbackDevice.QuadEncoder);
    	ifOn=false;
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void set(double s)
    {
    	climberTalon.set(s);
    }
    public void initDefaultCommand() {
        setDefaultCommand(new stopClimber());
    }
	@Override
	public double getRPM() {
		return climberTalon.getEncVelocity();
	}
}

