// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6135.robot.subsystems;

import org.usfirst.frc.team6135.robot.RobotMap;
import org.usfirst.frc.team6135.robot.commands.*;
import com.ctre.CANTalon;
import com.ctre.CANTalon.FeedbackDevice;



/**
 *
 */
public class Shooter extends baseSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon shooterTalon = RobotMap.shooterTalon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public Shooter()
    {
    	super("Shooter");
    	shooterTalon.setFeedbackDevice(FeedbackDevice.QuadEncoder);
    }
    public void initDefaultCommand() {
        setDefaultCommand(new stopShooter());
    }

	@Override
	public void set(double s) {
		shooterTalon.set(s);
		
	}

	@Override
	public double getRPM() {
		return shooterTalon.getEncVelocity();
	}
}

